version: '3.7'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
    web:
        build: .
        ports:
        - "5000:5000"
        volumes:
        - .:/code # 把當前資料夾 mount 掛載進去 container，這樣你可以直接在本地端專案資料夾改動檔案，container 裡面的檔案也會更動也不用重新 build image！

    prometheus:
      image: prom/prometheus:v2.1.0
      volumes:
        - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
        - ./alert_rules.yaml:/etc/prometheus/alert_rules.yaml
      command:
        - '--config.file=/etc/prometheus/prometheus.yaml'
      ports:
        - '9090:9090'

    grafana:
      image: grafana/grafana
      volumes:
          - grafana_data:/var/lib/grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=pass
      depends_on:
        - prometheus
      ports:
        - '3000:3000'   

    alertmanager:
      image: prom/alertmanager
      ports:
        - 9093:9093
      volumes:
        - ./alertmanager.yaml/:/etc/alertmanager/alertmanager.yaml
      restart: always
      command:
        - '--config.file=/etc/alertmanager/alertmanager.yaml'
        - '--storage.path=/alertmanager'    